all:
	pdflatex cover
	bibtex cover
	pdflatex cover
	pdflatex cover
	pdflatex appendix
	pdflatex appendix

clean: 
	rm -f *.out *.bbl *.synctex.gz *.blg *.aux *.dvi *.log *.ent paper.pdf *.ps *converted-to.pdf
