all:
	latex paper
	bibtex paper
	latex paper
	latex paper
	dvipdf paper
#	dvips -t letter paper.dvi 
#	ps2pdf paper.ps paper.pdf

clean: 
	rm -f *.out *.bbl *.synctex.gz *.blg *.aux *.dvi *.log *.ent *.ps *converted-to.pdf
