all:
	pdflatex paper
	bibtex paper
	pdflatex paper
	pdflatex paper

demo:
	pdflatex demo
	bibtex demo
	pdflatex demo
	pdflatex demo

clean:
	rm -f *.aux *.bbl *.blg *.log *.toc *.out paper.pdf demo.pdf
