all:
	xelatex -interaction=nonstopmode thesis
	biber thesis
	xelatex -interaction=nonstopmode thesis
	xelatex -interaction=nonstopmode thesis

basic:
	xelatex -interaction=nonstopmode thesis
	xelatex -interaction=nonstopmode thesis

latexmk:
	latexmk -xelatex -gg -silent -f thesis

clean: 
	rm -f *.out *.bbl *.synctex.gz *.blg *.aux *.dvi *.log *.ent *.ps *converted-to.pdf
