all:
	latex paper
	latex paper
	bibtex paper
	latex paper
	latex paper
	dvips paper
	ps2pdf paper.ps
#	dvipdfm -p letter paper.dvi

clean:
	rm -f *.bbl *.blg *.aux *.dvi *.log *.ent *.pdf *.gz *.fdb_latexmk
