all:
	pdflatex supplementary
	bibtex supplementary
	pdflatex supplementary
	pdflatex supplementary

clean: 
	rm -f *.out *.bbl *.synctex.gz *.blg *.aux *.dvi *.log *.ent paper.pdf *.ps *converted-to.pdf
