all:
	latex paper
	latex paper
	bibtex paper
	latex paper
	latex paper
	dvipdfm -p letter paper.dvi

dvi:
	latex paper
	latex paper
	bibtex paper
	latex paper
	latex paper

clean:
	rm -f *.log *.bbl *.blg *.aux *.dvi
