all:
	pdflatex aaai2021
	bibtex aaai2021
	pdflatex aaai2021
	pdflatex aaai2021
	pdflatex aaai2021
#	dvipdf aaai2021.dvi
#	dvipdfm -p letter aaai2021.dvi
#	dvips -t letter -Ppdf aaai2021.dvi -o aaai2021.ps
#	ps2pdf aaai2021.ps;rm -rf aaai2021.ps

#pictures:
#	bmeps -c search_kiwi.jpg search_kiwi.eps

clean: 
	rm -f *.bbl *.blg *.aux *.dvi *.log *.ent *converted*.pdf aaai2021.pdf *.ps *.out
